# Generated by Django 5.1.15 on 2026-09-01 14:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCase',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('outstanding_amount_ugx', models.DecimalField(decimal_places=2, max_digits=18)),
                ('collected_amount_ugx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('days_overdue', models.PositiveIntegerField(default=0)),
                ('escalation_level', models.CharField(choices=[('none', 'Standard Monitoring'), ('reminder_letter', 'Stage 1 - Reminder Notice'), ('formal_notice', 'Stage 2 - Formal Demand Letter'), ('legal_action', 'Stage 3 - Legal Action Escalation')], db_index=True, default='none', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active Recovery'), ('disputed', 'Disputed by Buyer'), ('resolved', 'Fully Recovered'), ('written_off', 'Written Off (Defaulted)')], db_index=True, default='active', max_length=20)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('promise_to_pay_date', models.DateField(blank=True, null=True)),
                ('promise_to_pay_amount_ugx', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='buyers.buyer')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_case', to='invoices.invoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Collection Case',
                'verbose_name_plural': 'Collection Cases',
                'ordering': ['-days_overdue', '-outstanding_amount_ugx'],
            },
        ),
        migrations.CreateModel(
            name='EscalationDocument',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('document_type', models.CharField(choices=[('reminder_letter', 'Friendly Reminder Letter'), ('demand_letter', 'Formal Demand Letter'), ('legal_notice', 'Statutory Notice of Intent to Sue')], default='demand_letter', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft Preview'), ('finalized', 'Finalized & Signed'), ('sent', 'Dispatched to Debtor')], default='draft', max_length=20)),
                ('deadline_days', models.PositiveIntegerField(default=7)),
                ('additional_notes', models.TextField(blank=True)),
                ('generated_by', models.CharField(default='Credit Officer', max_length=150)),
                ('finalized_by', models.CharField(blank=True, max_length=150, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('collection_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='collections.collectioncase')),
            ],
            options={
                'verbose_name': 'Escalation Document',
                'verbose_name_plural': 'Escalation Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
