# Generated by Django 5.1.15 on 2026-09-01 14:04

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('industry', models.CharField(default='General Industry', max_length=150)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('1000000000.00'), max_digits=18)),
                ('available_limit', models.DecimalField(decimal_places=2, default=Decimal('1000000000.00'), max_digits=18)),
                ('payment_terms_days', models.PositiveIntegerField(default=60, help_text='Standard credit terms in days')),
                ('credit_rating', models.CharField(choices=[('AAA', 'AAA - Prime Corporate'), ('AA', 'AA - High Grade'), ('A', 'A - Upper Medium Grade'), ('BBB', 'BBB - Investment Grade'), ('BB', 'BB - Speculative Grade'), ('B', 'B - Highly Speculative'), ('CCC', 'CCC - High Default Risk')], default='A', max_length=10)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Corporate Buyer',
                'verbose_name_plural': 'Corporate Buyers',
                'ordering': ['name'],
            },
        ),
    ]
