#!/usr/bin/env bash
# =============================================================================
# RIS Platform — One-shot staging bootstrap for AWS EC2
#
# Run this ONCE on the EC2 staging host. It is idempotent — re-running it is
# safe and will only fix the steps that aren't done yet.
#
# What it does:
#   1. Verifies Docker + Compose are installed
#   2. Clones the repo if missing (default: ~/RIS-Platform)
#   3. Writes a .env with strong random secrets (only if .env doesn't exist)
#   4. Prompts for a GHCR Personal Access Token and runs docker login
#   5. Runs deploy/deploy.sh (pull images → migrate → start containers)
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/256MMcode/RIS-Platform/develop/deploy/bootstrap-staging.sh | bash
# OR (after cloning):
#   bash deploy/bootstrap-staging.sh
#
# Environment overrides (all optional):
#   REPO_PATH=/path/to/checkout       — default ~/RIS-Platform
#   REPO_URL=https://...              — default github.com/256MMcode/RIS-Platform
#   STAGING_URL=https://staging.ris.ug — used in CORS_ALLOWED_ORIGINS
# =============================================================================

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[BOOTSTRAP]${NC} $1"; }
ok() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
    exit 1
}

# ── Config ────────────────────────────────────────────────────────────────────
REPO_PATH="${REPO_PATH:-$HOME/RIS-Platform}"
REPO_URL="${REPO_URL:-https://github.com/256MMcode/RIS-Platform.git}"
BRANCH="${BRANCH:-develop}"

log "Repo path: $REPO_PATH"
log "Repo URL:  $REPO_URL"
log "Branch:    $BRANCH"

# ── Step 1: Prerequisites ─────────────────────────────────────────────────────
log "Step 1/5 — Prerequisites"

command -v git >/dev/null 2>&1 || err "git is not installed. apt install git -y or yum install git -y"
command -v openssl >/dev/null 2>&1 || err "openssl is not installed."
command -v docker >/dev/null 2>&1 || err "Docker is not installed. See https://docs.docker.com/engine/install/"
docker info >/dev/null 2>&1 || err "Docker daemon not running. Run: sudo systemctl start docker"
docker compose version >/dev/null 2>&1 || err "docker compose v2 not available. Update Docker."
ok "git, openssl, docker, compose all present"

# ── Step 2: Clone or update repo ──────────────────────────────────────────────
log "Step 2/5 — Repo"

if [ -d "$REPO_PATH/.git" ]; then
    log "Repo already cloned at $REPO_PATH — updating"
    cd "$REPO_PATH"
    git fetch --quiet origin "$BRANCH"
    git reset --hard "origin/$BRANCH"
    ok "On origin/$BRANCH: $(git log -1 --oneline)"
else
    log "Cloning fresh into $REPO_PATH"
    git clone --branch "$BRANCH" "$REPO_URL" "$REPO_PATH"
    cd "$REPO_PATH"
    ok "Cloned at $(git log -1 --oneline)"
fi

# ── Step 3: .env (generate if missing) ────────────────────────────────────────
log "Step 3/5 — Environment file"

ENV_FILE="$REPO_PATH/.env"

if [ -f "$ENV_FILE" ]; then
    warn ".env already exists — leaving it untouched."
    warn "If you want fresh secrets, back it up and re-run:"
    warn "    mv .env .env.backup-\$(date +%Y%m%d-%H%M%S) && bash deploy/bootstrap-staging.sh"
else
    log "Generating .env with strong random secrets..."

    JWT_SECRET="$(openssl rand -hex 32)"
    ENCRYPTION_KEY="$(openssl rand -hex 32)"
    POSTGRES_PASSWORD="$(openssl rand -base64 24 | tr -d '=/+')"
    DB_USER="${POSTGRES_USER:-ris_user}"
    DB_NAME="${POSTGRES_DB:-ris_platform}"
    CORS_ORIGINS="${STAGING_URL:-https://staging.example.com}"

    cat >"$ENV_FILE" <<ENVEOF
# =============================================================================
# RIS Platform — staging environment
# Generated by deploy/bootstrap-staging.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit non-cryptographic fields below as needed; never commit this file.
# =============================================================================

NODE_ENV=production
PORT=4000

# --- Database ---
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${DB_NAME}
DATABASE_URL=postgresql://${DB_USER}:${POSTGRES_PASSWORD}@ris-postgres:5432/${DB_NAME}
DATABASE_POOL_MIN=2
DATABASE_POOL_MAX=10

# --- Redis ---
REDIS_URL=redis://ris-redis:6379

# --- Authentication ---
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=15m
REFRESH_TOKEN_EXPIRY=7d

# --- Encryption ---
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# --- CORS ---
# Comma-separated list of allowed origins. Set to your actual staging URL.
CORS_ALLOWED_ORIGINS=${CORS_ORIGINS}

# --- Frontend ---
FRONTEND_URL=${CORS_ORIGINS}

# --- Business rules ---
MAX_INVOICE_TENOR_DAYS=90
MIN_INVOICE_TENOR_DAYS=7
AML_FLAG_THRESHOLD_UGX=100000000
DUAL_AUTH_REQUIRED=true

# --- Rate limiting ---
RATE_LIMIT_AUTH_MAX=30
RATE_LIMIT_AUTH_WINDOW_MS=900000

# --- PROVIDER SANDBOX CREDENTIALS ---
# These are placeholders. Set real sandbox keys before testing payment flows.
# The server WILL refuse to start in production mode without them. Only EFT
# (bank ACH) is supported — mobile-money providers have been retired.
EFT_BANK_API_URL=https://sandbox.bank.example.ug/eft/v1
EFT_BANK_API_KEY=sandbox_eft_api_key
EFT_OUTPUT_DIR=/var/lib/ris/eft-output
EFT_BANK_CODE=RIS001

# --- Email (set real SES creds before user-facing email works) ---
SES_SMTP_HOST=email-smtp.eu-central-1.amazonaws.com
SES_SMTP_PORT=587
SES_SMTP_USER=placeholder
SES_SMTP_PASS=placeholder
SES_FROM_DEFAULT=noreply@raphaintegrated.com
SES_FROM_CONFIRM=confirm@raphaintegrated.com
SES_FROM_PAYMENTS=payments@raphaintegrated.com
SES_FROM_KYC=kyc@raphaintegrated.com
SES_FROM_COLLECTIONS=collections@raphaintegrated.com
SES_FROM_SUPPORT=support@raphaintegrated.com
EMAIL_FROM="RIS Platform <noreply@raphaintegrated.com>"

# --- SMS (Africa's Talking) ---
AT_API_KEY=sandbox
AT_USERNAME=sandbox
AT_SENDER_ID=RIS
ENVEOF

    chmod 600 "$ENV_FILE"
    ok ".env generated with 256-bit JWT_SECRET and ENCRYPTION_KEY"
    warn "Open $ENV_FILE and review CORS_ALLOWED_ORIGINS / FRONTEND_URL / provider keys."
fi

# ── Step 4: GHCR login ────────────────────────────────────────────────────────
log "Step 4/5 — GHCR login"

if docker info 2>/dev/null | grep -q "Username:"; then
    ok "Docker already has credentials configured"
elif [ -f "$HOME/.docker/config.json" ] && grep -q "ghcr.io" "$HOME/.docker/config.json" 2>/dev/null; then
    ok "GHCR credentials present in ~/.docker/config.json"
else
    warn "Docker is not logged in to ghcr.io yet."
    warn "Create a GitHub Personal Access Token with the 'read:packages' scope:"
    warn "    https://github.com/settings/tokens/new?scopes=read:packages&description=ris-staging-ec2"
    echo ""
    read -p "GitHub username: " GH_USERNAME
    read -rsp "GitHub PAT (input hidden): " GH_PAT
    echo ""
    echo "$GH_PAT" | docker login ghcr.io -u "$GH_USERNAME" --password-stdin
    unset GH_PAT
    ok "Logged in to ghcr.io"
fi

# ── Step 5: Deploy ────────────────────────────────────────────────────────────
log "Step 5/5 — Running deploy.sh"

cd "$REPO_PATH"
./deploy/deploy.sh

echo ""
ok "============================================"
ok "  Staging is up. Verify at your STAGING_URL"
ok "============================================"
echo ""
log "Next steps:"
log "  1. Add these GitHub secrets so future pushes auto-deploy:"
log "       STAGING_HOST     = $(hostname -f 2>/dev/null || hostname)"
log "       STAGING_SSH_USER = $(whoami)"
log "       STAGING_SSH_KEY  = <contents of the .pem you SSH with>"
log "     See deploy/CONFIGURE-GITHUB-SECRETS.md for the walkthrough."
log "  2. Open STAGING_URL in a browser; if you've set up DNS, the site is live."
