# Generated by Django 5.1.15 on 2026-09-01 14:09

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('category', models.CharField(choices=[('weight', '5-Factor Risk Model Weights'), ('threshold', 'Operational Thresholds & Triggers'), ('limit', 'Facility Exposure Limits'), ('rate', 'Base Pricing Rates & Margins')], default='weight', max_length=30)),
                ('min_value', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
                ('max_value', models.DecimalField(decimal_places=4, default=Decimal('100.0'), max_digits=18)),
                ('unit', models.CharField(default='%', max_length=20)),
            ],
            options={
                'verbose_name': 'Risk Configuration',
                'verbose_name_plural': 'Risk Configurations',
                'ordering': ['category', 'key'],
            },
        ),
    ]
