# Generated by Django 5.1.15 on 2026-09-01 14:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('company', models.CharField(db_index=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tin', models.CharField(blank=True, help_text='URA Tax Identification Number', max_length=50)),
                ('industry', models.CharField(default='General Commerce', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('name', models.CharField(help_text="Contact person's full name", max_length=255)),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('risk_band', models.CharField(choices=[('low', 'Low Risk (Tier 1)'), ('medium', 'Medium Risk (Tier 2)'), ('high', 'High Risk (Tier 3)'), ('critical', 'Critical Risk (Tier 4)')], db_index=True, default='low', max_length=20)),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                ('total_outstanding_ugx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_limit_ugx', models.DecimalField(decimal_places=2, default=Decimal('500000000.00'), max_digits=18)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('doc_type', models.CharField(choices=[('certificate_of_incorporation', 'Certificate of Incorporation'), ('tax_clearance', 'URA Tax Clearance Certificate'), ('bank_statements_6m', '6-Month Certified Bank Statements'), ('director_id', 'Director National ID / Passport'), ('trading_license', 'Trading License')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
