# Generated by Django 5.1.15 on 2026-09-01 14:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('face_value_ugx', models.DecimalField(decimal_places=2, max_digits=18)),
                ('collected_amount_ugx', models.DecimalField(decimal_places=2, max_digits=18)),
                ('advance_amount_ugx', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_earned_ugx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('penalty_income_ugx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('facility_repayment_ugx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bank_cost_paid_ugx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_profit_ugx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending Repayment Allocation'), ('facility_repaid', 'Partner Bank Facility Repaid'), ('profit_booked', 'Platform Gross Margin Realized'), ('closed', 'Settlement Ledger Closed & Audited')], db_index=True, default='pending', max_length=30)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('accounting_notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='buyers.buyer')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='invoices.invoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Settlement Record',
                'verbose_name_plural': 'Settlement Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
