# Generated by Django 5.1.15 on 2026-09-01 14:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('face_value_ugx', models.DecimalField(decimal_places=2, help_text='Total invoice face value in UGX', max_digits=18)),
                ('advance_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Percentage advance rate (e.g. 80%)', max_digits=5)),
                ('advance_amount_ugx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross advance payout (Face Value * Advance Rate)', max_digits=18)),
                ('discount_fee_ugx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total factoring discount charge', max_digits=18)),
                ('net_advance_ugx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net liquidity disbursed to supplier', max_digits=18)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified by Buyer'), ('priced', 'Priced & Risk Evaluated'), ('approved', 'Approved for Funding'), ('funded', 'Funded / Disbursed'), ('collecting', 'In Collection'), ('collected', 'Fully Collected'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=30)),
                ('risk_score', models.PositiveIntegerField(default=75, help_text='Composite 5-factor risk score (0-100)')),
                ('risk_grade', models.CharField(choices=[('low', 'Low Risk (Grade A)'), ('medium', 'Medium Risk (Grade B)'), ('high', 'High Risk (Grade C)'), ('critical', 'Critical Risk (Grade D)')], default='low', max_length=20)),
                ('score_factors', models.JSONField(blank=True, default=dict, help_text='5-factor breakdown scores')),
                ('pricing_breakdown', models.JSONField(blank=True, default=dict, help_text='Rate breakdown (Base, Spread, Margin, Annual Rate)')),
                ('verification_token', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notice_of_assignment_signed', models.BooleanField(default=False)),
                ('approval_tier', models.PositiveIntegerField(default=1, help_text='Tier 1 (<50M), Tier 2 (<200M), Tier 3 (<500M), Tier 4 (>500M)')),
                ('rejection_reason', models.TextField(blank=True)),
                ('credit_officer_notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='buyers.buyer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('doc_type', models.CharField(choices=[('commercial_invoice', 'Commercial Invoice'), ('delivery_note', 'Goods Received / Delivery Note'), ('purchase_order', 'Purchase Order'), ('notice_of_assignment', 'Notice of Assignment (Signed)')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Document',
                'verbose_name_plural': 'Invoice Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
