# Generated by Django 5.1.15 on 2026-09-01 14:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('amount_ugx', models.DecimalField(decimal_places=2, help_text='Net advance payout in UGX', max_digits=18)),
                ('provider', models.CharField(choices=[('EFT', 'Bank EFT (Bank of Uganda ACH)'), ('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money'), ('MOCK', 'Mock Simulation Rail')], default='EFT', max_length=30)),
                ('status', models.CharField(choices=[('pending_signature', 'Needs 1st Signature'), ('partially_signed', 'Needs 2nd Signature'), ('authorized', 'Dual-Authorized'), ('processing', 'Processing Rail Execution'), ('disbursed', 'Disbursed to Supplier'), ('failed', 'Execution Failed')], db_index=True, default='pending_signature', max_length=30)),
                ('dual_auth_user1_at', models.DateTimeField(blank=True, null=True)),
                ('dual_auth_user2_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('sla_deadline', models.DateTimeField(help_text='72-hour disbursement SLA deadline')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='buyers.buyer')),
                ('dual_auth_user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sign_1', to=settings.AUTH_USER_MODEL)),
                ('dual_auth_user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sign_2', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
